# Generated by Django 4.2.2 on 2023-06-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyect',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Dirección web'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='descrition',
            field=models.TextField(verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='image',
            field=models.ImageField(upload_to='projects', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='proyect',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edicion'),
        ),
    ]
